#!/usr/bin/env node
/**
 * Image pipeline.
 *
 * Reads every image in assets/images, writes a web-sized .webp into
 * public/images, and regenerates src/lib/image-blur.ts with an inline
 * LQIP for each one.
 *
 *   npm run images
 *
 * Filenames become the `Media.src` keys used by the content layer, so
 * name source files semantically (portrait-open-hands.jpg), or add an
 * entry to RENAMES below for files that arrive with camera names.
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SOURCE_DIR = path.resolve("assets/images");
const OUTPUT_DIR = path.resolve("public/images");
const BLUR_MODULE = path.resolve("src/lib/image-blur.ts");

const MAX_WIDTH = 1600;
const MAX_HEIGHT = 2000;
const QUALITY = 82;

/** Camera filename → semantic name. Extend as new shoots come in. */
const RENAMES = {
  "TSA06702-1": "portrait-open-hands",
  "TSA06852-1": "portrait-joyful-white",
  "TSA06712": "portrait-prayer",
  "TSA06827": "portrait-white-standing",
  "TSA06843-1": "portrait-seated-profile",
  "TSA06855-A": "worship-painterly",
  "TSA06868-1": "portrait-burgundy-close",
  "TSA06861": "portrait-burgundy-hands",
  "TSA06885-1": "portrait-burgundy-full",
  "TSA06524": "editorial-veil-close",
  "TSA06492": "editorial-veil-seated",
  "TSA06557 1": "editorial-veil-leaning",
  "TSA06544": "editorial-veil-chest",
  "TSA06584": "editorial-veil-twirl",
  "TSA06636": "editorial-veil-motion",
  "TSA06416": "editorial-monochrome",
  "TSA06439": "editorial-raised-hand",
  "TSA06443": "editorial-stance",
  "TSA05808": "garden-portrait-hat",
  "TSA05763": "garden-leaning-log",
  "TSA05798": "garden-seated-log",
  "TSA05874": "garden-swing-laugh",
  "TSA05902": "garden-swing-reach",
  "TSA05698": "garden-twirl",
  "TSA05817": "garden-trees",
  "TSA05827": "garden-path",
  "TSA05836": "garden-forest-wide",
};

const SUPPORTED = new Set([".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff"]);

const slugify = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

async function main() {
  await mkdir(OUTPUT_DIR, { recursive: true });

  const entries = await readdir(SOURCE_DIR, { withFileTypes: true });
  const images = entries
    .filter((entry) => entry.isFile() && SUPPORTED.has(path.extname(entry.name).toLowerCase()))
    .map((entry) => entry.name)
    .sort();

  if (images.length === 0) {
    console.warn(`No source images found in ${SOURCE_DIR}`);
    return;
  }

  const blurEntries = [];

  for (const filename of images) {
    const stem = path.basename(filename, path.extname(filename));
    const name = RENAMES[stem] ?? slugify(stem);
    const source = path.join(SOURCE_DIR, filename);

    const pipeline = sharp(source)
      .rotate()
      .resize({ width: MAX_WIDTH, height: MAX_HEIGHT, fit: "inside", withoutEnlargement: true });

    await pipeline.clone().webp({ quality: QUALITY, effort: 6 }).toFile(
      path.join(OUTPUT_DIR, `${name}.webp`),
    );

    const blur = await pipeline.clone().resize(12).jpeg({ quality: 30 }).toBuffer();
    blurEntries.push([name, `data:image/jpeg;base64,${blur.toString("base64")}`]);

    console.log(`✓ ${filename} → ${name}.webp`);
  }

  blurEntries.sort(([a], [b]) => a.localeCompare(b));

  const module = [
    "// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.",
    "export const imageBlurData: Record<string, string> = {",
    ...blurEntries.map(([name, data]) => `  ${JSON.stringify(name)}: ${JSON.stringify(data)},`),
    "};",
    "",
  ].join("\n");

  await writeFile(BLUR_MODULE, module, "utf8");
  console.log(`\nWrote ${blurEntries.length} images and regenerated ${path.relative(process.cwd(), BLUR_MODULE)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
